
```{r, setup1, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# source("../../input/code/knitr_hooks.R")

# fra_pdf = function(file, width, height) {
#   cairo_pdf(file, width = width, height = height, pointsize = 10, family = "PT Sans")
#   # svglite::svglite(file, width = width, height = height, pointsize = 10)
# }
library(knitr)
opts_chunk$set(list(echo=FALSE,
                    fig.path = paste0('./figure_',cntrycode,'/'),
                    eval=TRUE,
                    cache=FALSE,
                    warning=FALSE,
                    message=FALSE,
                    results='asis')
)

# plot spesification
html_width <- 6
html_height <- 5.5
tall_height <- 11
```


```{r, setup-code, eval=TRUE}
knitr::read_chunk("../../input/code/figures_tables.R")
```


```{r, setup}
```


# Introduction

```{r,introtexts, results = "asis"}
```

## Key indicators

```{r,cntrytable, eval = include_tables}
```


****

# Forest area and land use

```{r,line_forest_area_pie_land_use, fig.height = small_height, eval = include_plots, out.height=".75\\textwidth", fig.show = "hold", fig.align="center"}
```


```{r,land_use_comparison, fig.width = tall_height, fig.height = small_width, eval = include_plots, out.height= "\\textwidth",  out.width= "\\textheight", out.extra='angle=90'}
```

****

# Forest types

```{r,line_forest_type_pie_forest_type, fig.height = small_height, eval = include_plots, out.height=".75\\textwidth", fig.show = "hold", fig.align="center"}
```


```{r,forest_type_comparison, fig.width = tall_height, fig.height = small_width, eval = include_plots, out.height= "\\textwidth",  out.width= "\\textheight", out.extra='angle=90'}
```

****

# Fires, designation, ownership and carbon

```{r,line_forest_fires_line_forest_designation_trends, fig.height = small_height, eval = include_plots, out.height=".75\\textwidth", fig.show = "hold", fig.align="center"}
```

****

```{r,pie_ownership_line_carbon, fig.height = small_height, eval = include_plots, out.height=".75\\textwidth", fig.show = "hold", fig.align="center"}
```


****

# Production

```{r,table_production, eval = include_tables}
```
